# Generated by Django 5.0 on 2024-01-13 13:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=10000000)),
                ('company', models.CharField(max_length=10000000, null=True)),
                ('location', models.CharField(max_length=10000000, null=True)),
                ('salary', models.CharField(max_length=10000000, null=True)),
                ('job_type', models.CharField(max_length=10000000, null=True)),
                ('Job_Description', models.CharField(max_length=10000000)),
                ('link', models.CharField(max_length=10000000)),
                ('on_click', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
