# Generated by Django 5.0 on 2024-01-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0002_alter_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='on_click',
            field=models.IntegerField(default=0),
        ),
    ]
