# Generated by Django 5.0 on 2024-02-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0003_alter_job_on_click'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table='Job',
        ),
    ]
