# Generated by Django 5.0 on 2024-02-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0004_alter_job_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table=None,
        ),
    ]
