# Generated by Django 5.0 on 2024-02-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0007_user_role_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
